# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

# paths to include during linting. `--path` is ignored if present.
#included:
#  - OpenFlight

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods
  - OpenFlight/Constants/
  - OpenFlight/Resources/Protobuf/

line_length:
  warning: 160
  error: 200

file_length:
  warning: 700
  error: 1000

function_parameter_count:
  warning: 7
  error: 10

cyclomatic_complexity:
  warning: 15
  error: 20

function_body_length:
  warning: 100
  error: 150

identifier_name:
   max_length:
    warning: 50
    error: 60
