platform :ios, '14.0'

target 'OpenFlightApp' do
  use_frameworks!
  pod 'GroundSdk', '7.7.0-rc1'
  pod 'ArsdkEngine', '7.7.0-rc1'
  pod 'SdkCore', '7.7.0-rc1'
  pod 'OpenFlightCore', '7.7.0-rc1'
  pod 'SwiftGen', '6.5.1'
  pod 'SwiftLint', '0.50.3'
  pod 'Reusable', '4.1.2'
  pod 'SwiftyUserDefaults', '5.3.0'
  pod 'KeychainAccess', '4.2.2'
  pod 'lottie-ios', '4.0.1'
  pod 'ArcGIS-Runtime-SDK-iOS', '~> 100.15'
end
