// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: parrot/protobuf/extensions.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in extensions.proto.

// MARK: - Extension Properties

// Swift Extensions on the exteneded Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_EnumOptions {

  var enumDoc: String {
    get {return getExtensionValue(ext: Extensions_enum_doc) ?? String()}
    set {setExtensionValue(ext: Extensions_enum_doc, value: newValue)}
  }
  /// Returns true if extension `Extensions_enum_doc`
  /// has been explicitly set.
  var hasEnumDoc: Bool {
    return hasExtensionValue(ext: Extensions_enum_doc)
  }
  /// Clears the value of extension `Extensions_enum_doc`.
  /// Subsequent reads from it will return its default value.
  mutating func clearEnumDoc() {
    clearExtensionValue(ext: Extensions_enum_doc)
  }
}

extension SwiftProtobuf.Google_Protobuf_EnumValueOptions {

  var enumValueDoc: String {
    get {return getExtensionValue(ext: Extensions_enum_value_doc) ?? String()}
    set {setExtensionValue(ext: Extensions_enum_value_doc, value: newValue)}
  }
  /// Returns true if extension `Extensions_enum_value_doc`
  /// has been explicitly set.
  var hasEnumValueDoc: Bool {
    return hasExtensionValue(ext: Extensions_enum_value_doc)
  }
  /// Clears the value of extension `Extensions_enum_value_doc`.
  /// Subsequent reads from it will return its default value.
  mutating func clearEnumValueDoc() {
    clearExtensionValue(ext: Extensions_enum_value_doc)
  }
}

extension SwiftProtobuf.Google_Protobuf_FieldOptions {

  var fieldDoc: String {
    get {return getExtensionValue(ext: Extensions_field_doc) ?? String()}
    set {setExtensionValue(ext: Extensions_field_doc, value: newValue)}
  }
  /// Returns true if extension `Extensions_field_doc`
  /// has been explicitly set.
  var hasFieldDoc: Bool {
    return hasExtensionValue(ext: Extensions_field_doc)
  }
  /// Clears the value of extension `Extensions_field_doc`.
  /// Subsequent reads from it will return its default value.
  mutating func clearFieldDoc() {
    clearExtensionValue(ext: Extensions_field_doc)
  }
}

extension SwiftProtobuf.Google_Protobuf_FileOptions {

  var olympePackage: String {
    get {return getExtensionValue(ext: Extensions_olympe_package) ?? String()}
    set {setExtensionValue(ext: Extensions_olympe_package, value: newValue)}
  }
  /// Returns true if extension `Extensions_olympe_package`
  /// has been explicitly set.
  var hasOlympePackage: Bool {
    return hasExtensionValue(ext: Extensions_olympe_package)
  }
  /// Clears the value of extension `Extensions_olympe_package`.
  /// Subsequent reads from it will return its default value.
  mutating func clearOlympePackage() {
    clearExtensionValue(ext: Extensions_olympe_package)
  }
}

extension SwiftProtobuf.Google_Protobuf_MessageOptions {

  var messageDoc: String {
    get {return getExtensionValue(ext: Extensions_message_doc) ?? String()}
    set {setExtensionValue(ext: Extensions_message_doc, value: newValue)}
  }
  /// Returns true if extension `Extensions_message_doc`
  /// has been explicitly set.
  var hasMessageDoc: Bool {
    return hasExtensionValue(ext: Extensions_message_doc)
  }
  /// Clears the value of extension `Extensions_message_doc`.
  /// Subsequent reads from it will return its default value.
  mutating func clearMessageDoc() {
    clearExtensionValue(ext: Extensions_message_doc)
  }

  var onSuccess: String {
    get {return getExtensionValue(ext: Extensions_on_success) ?? String()}
    set {setExtensionValue(ext: Extensions_on_success, value: newValue)}
  }
  /// Returns true if extension `Extensions_on_success`
  /// has been explicitly set.
  var hasOnSuccess: Bool {
    return hasExtensionValue(ext: Extensions_on_success)
  }
  /// Clears the value of extension `Extensions_on_success`.
  /// Subsequent reads from it will return its default value.
  mutating func clearOnSuccess() {
    clearExtensionValue(ext: Extensions_on_success)
  }

  var onFailure: String {
    get {return getExtensionValue(ext: Extensions_on_failure) ?? String()}
    set {setExtensionValue(ext: Extensions_on_failure, value: newValue)}
  }
  /// Returns true if extension `Extensions_on_failure`
  /// has been explicitly set.
  var hasOnFailure: Bool {
    return hasExtensionValue(ext: Extensions_on_failure)
  }
  /// Clears the value of extension `Extensions_on_failure`.
  /// Subsequent reads from it will return its default value.
  mutating func clearOnFailure() {
    clearExtensionValue(ext: Extensions_on_failure)
  }

  var support: [String] {
    get {return getExtensionValue(ext: Extensions_support) ?? []}
    set {setExtensionValue(ext: Extensions_support, value: newValue)}
  }
  /// Returns true if extension `Extensions_support`
  /// has been explicitly set.
  var hasSupport: Bool {
    return hasExtensionValue(ext: Extensions_support)
  }
  /// Clears the value of extension `Extensions_support`.
  /// Subsequent reads from it will return its default value.
  mutating func clearSupport() {
    clearExtensionValue(ext: Extensions_support)
  }

}

// MARK: - File's ExtensionMap: Extensions_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Extensions_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Extensions_olympe_package,
  Extensions_message_doc,
  Extensions_field_doc,
  Extensions_on_success,
  Extensions_on_failure,
  Extensions_support,
  Extensions_enum_doc,
  Extensions_enum_value_doc
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

let Extensions_olympe_package = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_FileOptions>(
  _protobuf_fieldNumber: 65000,
  fieldName: "olympe_package"
)

let Extensions_message_doc = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 65001,
  fieldName: "message_doc"
)

let Extensions_field_doc = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_FieldOptions>(
  _protobuf_fieldNumber: 65002,
  fieldName: "field_doc"
)

let Extensions_on_success = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 65003,
  fieldName: "on_success"
)

let Extensions_on_failure = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 65004,
  fieldName: "on_failure"
)

let Extensions_support = SwiftProtobuf.MessageExtension<SwiftProtobuf.RepeatedExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 65005,
  fieldName: "support"
)

let Extensions_enum_doc = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumOptions>(
  _protobuf_fieldNumber: 65006,
  fieldName: "enum_doc"
)

let Extensions_enum_value_doc = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_EnumValueOptions>(
  _protobuf_fieldNumber: 65007,
  fieldName: "enum_value_doc"
)
